### ISSUE TITLE
 Error when running the bot

### ISSUE THREAD

**Issue by Y345ez** [Ganyu-Studios/stelle-music#3]
when I run the bot it will throw this error
![image](https://github.com/Ganyu-Studios/stelle-music/assets/94993680/10da4f32-956d-47f2-937a-1ab2aa1e3141)

**Comment by PancitoPues** [comment]
Give it the permissions your application needs on your server...

**Comment by Y345ez** [comment]
i did in the server and in the discord and in OAuth2

**Comment by EvilG-MC** [comment]
Make sure to change the server ids in [Stelle configuration](https://github.com/Ganyu-Studios/stelle-music/blob/main/src/structures/utils/data/Configuration.ts#L13)

**Comment by Y345ez** [comment]
ok now i get this 
![image](https://github.com/Ganyu-Studios/stelle-music/assets/94993680/9ad46a28-1b2a-4662-9449-376058bf3f53)
and 
![image](https://github.com/Ganyu-Studios/stelle-music/assets/94993680/706c1116-720b-41c0-922f-e792ecbf32be)

**Comment by Y345ez** [comment]
and it is not my MongoDB connection

**Comment by EvilG-MC** [comment]
> and it is not my MongoDB connection

I need a little more information. Stelle needs a MongoDB connection.

**Comment by EvilG-MC** [comment]
I think I know what it is, I'm going to investigate and if I get results, I'll fix it.

**Comment by Y345ez** [comment]
> > and it is not my MongoDB connection
> 
> I need a little more information. Stelle needs a MongoDB connection.

the mongoDB is connected to the bot

**Comment by EvilG-MC** [comment]
> > > and it is not my MongoDB connection
> > 
> > 
> > I need a little more information. Stelle needs a MongoDB connection.
> 
> the mongoDB is connected to the bot

According to prism documentation, and that was something I missed.... Prisma needs a name for the DB. You can check [this commit](https://github.com/Ganyu-Studios/stelle-music/commit/7fb61c48db0132b3c499f3d42f6dd6cf679cfead#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cR22)

**Comment by EvilG-MC** [comment]
Is this still active or can I close it now?

**Comment by EvilG-MC** [comment]
I'll mark this as resolved, if anything happens open another issue.
